# Generated by Django 4.2.5 on 2023-10-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="employee_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.employee",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="employee_id",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
