# Generated by Django 4.2.5 on 2023-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_employee_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="employee_profile",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="Amy", max_length=255),
        ),
    ]
