# Generated by Django 4.2.5 on 2023-10-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="product_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="menu.product",
            ),
        ),
    ]
